### ISSUE TITLE
why i need to open server first,then my client can find it...

### ISSUE THREAD

**Issue by xiaolongww** [Abdelfattah-Radwan/Fish-Networking-Discovery#2]
i found a strange thing: when i open server first,my client can find it;  
but  if i open client first ,my  client cant find server.

now i use a timer to solve it: 2 secs later,if my client cant find it,it will stopSearching first,then 
startSearching again.

maybe you can give a better method 👍 :D

thanks in advance!

**Comment by xiaolongww** [comment]
so sad,the method will throw a error : Cannot access a disposed object.
Object name: 'System.Net.Sockets.UdpClient'.  at System.Net.Sockets.UdpClient.EndReceive

**Comment by BlueVolt1** [comment]
I had a similar error and I editet the SearchForServersAsync() method

`private async void SearchForServersAsync()
		{
			byte[] secretBytes = Encoding.UTF8.GetBytes(secret);

			IPEndPoint endPoint = new(IPAddress.Broadcast, port);

			while (_clientUdpClient != null)
			{
				await Task.Delay(TimeSpan.FromSeconds(discoveryInterval));

				if (_clientUdpClient == null)
					continue;

				try
				{
					await _clientUdpClient.SendAsync(secretBytes, secretBytes.Length, endPoint);

					UdpReceiveResult result = await _clientUdpClient.ReceiveAsync();

					if (BitConverter.ToBoolean(result.Buffer, 0))
					{
						ServerFoundCallback?.Invoke(result.RemoteEndPoint);

						StopSearchingForServers();
					}
				}
				catch (ObjectDisposedException)
				{
					break;
				}
			}
		}`

**Comment by xiaolongww** [comment]
ok,i got the code from the email. thanks!
now i can use my timer and the code!

the code:
`private async void SearchForServersAsync()
		{

			byte[] secretBytes = Encoding.UTF8.GetBytes(secret);
			IPEndPoint endPoint = new(IPAddress.Broadcast, port);
			while (_clientUdpClient != null)
			{
				await Task.Delay(TimeSpan.FromSeconds(discoveryInterval));
				if (_clientUdpClient == null)
					continue;
				try
				{
					await _clientUdpClient.SendAsync(secretBytes, secretBytes.Length, endPoint);
					UdpReceiveResult result = await _clientUdpClient.ReceiveAsync();
					if (BitConverter.ToBoolean(result.Buffer, 0))
					{
						ServerFoundCallback?.Invoke(result.RemoteEndPoint);
						StopSearchingForServers();
					}
				}
				catch (ObjectDisposedException)
				{
					break;
				}
			}


		}`

my timer:

`using FishNet;
using FishNet.Discovery;
using FishNet.Managing;
using FishNet.Transporting;
using System.Collections;
using System.Collections.Generic;
using System.Net;
using UnityEngine;

public class ClientConn : MonoBehaviour
{

    [SerializeField]
    private NetworkDiscovery _networkDiscovery;


    public List<string> _endPoints = new List<string>();

    private void Start()
    {
        InstanceFinder.ClientManager.OnClientConnectionState += ClientManager_OnClientConnectionState;
        _networkDiscovery = FindObjectOfType<NetworkDiscovery>();
        _networkDiscovery.ServerFoundCallback += HandleEndPoint;
#if !UNITY_SERVER
         StartCoroutine(ConnManage());
#endif

    }

    void HandleEndPoint(IPEndPoint endPoint)
    {
        if (!_endPoints.Contains(endPoint.ToString()))
            _endPoints.Add(endPoint.Address.ToString());

    }
 
    private void ClientManager_OnClientConnectionState(FishNet.Transporting.ClientConnectionStateArgs args)
    {
        if (args.ConnectionState == LocalConnectionState.Starting)
        {
            StopAllCoroutines();
        }
        else if (args.ConnectionState == LocalConnectionState.Stopped)
        {
            StopAllCoroutines();
            StartCoroutine(ConnManage());
        }
    }

    IEnumerator ConnManage()
    {
        //为了解决网络发现的问题：先开客户端再开服务器找不到；而先开服务器再开客户端才找的到
        while (_endPoints.Count <= 0)
        {
            yield return new WaitForSeconds(2f);


            Debug.Log("-----------重启搜寻服务器---------");
            _networkDiscovery.StopSearchingForServers();
            _networkDiscovery.StartSearchingForServers();

        }
        InstanceFinder.ClientManager.StartConnection(_endPoints[0]);
        _endPoints = new List<string>();
    }

   
}
`

**Comment by BlueVolt1** [comment]
Hi @xiaolongww 
I have some hard times trying to configure Discovery.
I can connect to ip's without any problems but I never find any servers.
Even if I start the host first or the client, they never connect together.

**Could you show how you setup ip's? (the code)**

**Comment by Abdelfattah-Radwan** [comment]
This issue has been addressed in an update that is being released soon.
